# Generated by Django 3.0.2 on 2020-03-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagine', '0015_auto_20200306_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='last_updated',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='last_updated',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
