# Generated by Django 3.0.5 on 2020-04-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200403_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sector',
            field=models.CharField(choices=[('0-NO', 'No'), ('3-FI', 'No, solo i figli'), ('1-YC', 'Sì, con il corso'), ('2-NC', 'Sì, senza corso')], default='0-NO', max_length=4, verbose_name='Corri con noi?'),
        ),
    ]
