# Generated by Django 3.0.5 on 2020-04-15 20:32

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200415_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full', models.CharField(max_length=32, verbose_name='Giorno e ora')),
                ('abbrev', models.CharField(max_length=8, verbose_name='Abbreviazione')),
            ],
            options={
                'verbose_name': 'Orario',
                'verbose_name_plural': 'Orari',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='course_alt',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Altro orario'),
        ),
        migrations.AddField(
            model_name='profile',
            name='course_membership',
            field=models.CharField(blank=True, choices=[('INTU', 'Integrazione per materiale socio UISP'), ('INTF', 'Integrazione per materiale socio FIDAL')], help_text='Solo se si segue un corso', max_length=4, null=True, verbose_name='Federazione / Ente sportivo'),
        ),
        migrations.AddField(
            model_name='profile',
            name='med_cert',
            field=models.FileField(blank=True, null=True, upload_to=users.models.user_directory_path, verbose_name='Certificato medico'),
        ),
        migrations.AddField(
            model_name='profile',
            name='no_course_membership',
            field=models.CharField(blank=True, choices=[('UNA', 'UISP non agonistico'), ('UA', 'UISP agonistico'), ('FID', 'FIDAL agonistico')], help_text='Solo se non si segue un corso', max_length=4, null=True, verbose_name='Federazione / Ente sportivo'),
        ),
        migrations.AddField(
            model_name='profile',
            name='privacy',
            field=models.FileField(blank=True, null=True, upload_to=users.models.user_directory_path, verbose_name='Privacy'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sign_up',
            field=models.FileField(blank=True, null=True, upload_to=users.models.user_directory_path, verbose_name='Richiesta di tesseramento'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='profile',
            name='course',
            field=models.ManyToManyField(blank=True, to='users.CourseSchedule', verbose_name='Orari scelti'),
        ),
    ]
