# Generated by Django 3.0.5 on 2020-04-16 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200415_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_parent', to=settings.AUTH_USER_MODEL, verbose_name='Genitore'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(help_text='Via/Piazza, civico, CAP, Città', max_length=100, null=True, verbose_name='Indirizzo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='course_alt',
            field=models.CharField(blank=True, help_text="Solo se si è selezionato 'Altro'", max_length=100, null=True, verbose_name='Altro orario'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='course_membership',
            field=models.CharField(choices=[('INTU', 'Integrazione per materiale socio UISP'), ('INTF', 'Integrazione per materiale socio FIDAL')], max_length=4, null=True, verbose_name='Federazione / Ente sportivo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='Data di nascita'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fiscal_code',
            field=models.CharField(max_length=16, null=True, validators=[users.validators.validate_codice_fiscale], verbose_name='Codice fiscale'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('F', 'Femmina'), ('M', 'Maschio')], max_length=1, null=True, verbose_name='Sesso'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nationality',
            field=models.CharField(max_length=50, null=True, verbose_name='Nazionalità'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='no_course_membership',
            field=models.CharField(choices=[('UNA', 'UISP non agonistico'), ('UA', 'UISP agonistico'), ('FID', 'FIDAL agonistico')], max_length=4, null=True, verbose_name='Federazione / Ente sportivo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=50, null=True, verbose_name='Telefono/i'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='place_of_birth',
            field=models.CharField(max_length=50, null=True, verbose_name='Luogo di nascita'),
        ),
    ]
