# Generated by Django 3.0.5 on 2020-04-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200416_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_trusted',
            field=models.BooleanField(default=False, verbose_name='Persona conosciuta'),
        ),
    ]
