# Generated by Django 3.0.5 on 2020-04-18 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200418_2304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Iscritto', 'verbose_name_plural': 'Iscritti'},
        ),
        migrations.CreateModel(
            name='MemberPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('amount', models.FloatField(default=0.0, verbose_name='Importo')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_payments', to='users.Profile')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamenti',
            },
        ),
    ]
