# Generated by Django 3.0.5 on 2020-04-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200418_2314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberpayment',
            options={'ordering': ('-date',), 'verbose_name': 'Pagamento', 'verbose_name_plural': 'Pagamenti'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('user__last_name', 'user__first_name', 'user__username'), 'verbose_name': 'Iscritto', 'verbose_name_plural': 'Iscritti'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Utente', 'verbose_name_plural': 'Utenti'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='mc_state',
            field=models.CharField(blank=True, choices=[('0-NF', 'Manca il file'), ('02NI', 'Mancante, invia notifica'), ('04NN', 'Mancante, notificato'), ('1-VF', 'Verifica file'), ('2-RE', 'Regolare'), ('6-IS', 'In scadenza'), ('62II', 'In scadenza, invia notifica'), ('64IN', 'In scadenza, notificato'), ('3-SV', 'Scaduto, da verificare'), ('4-SI', 'Scaduto, invia notifica'), ('5-NI', 'Scaduto, notificato')], max_length=4, null=True, verbose_name='Stato del CM/CMA'),
        ),
    ]
