# Generated by Django 3.0.6 on 2020-05-29 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200422_2352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('last_name', 'first_name', 'username'), 'verbose_name': 'Utente', 'verbose_name_plural': 'Utenti'},
        ),
    ]
