# Generated by Django 3.0.7 on 2020-06-16 16:17

from django.db import migrations
import private_storage.fields
import private_storage.storage.files
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200529_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sign_up',
            field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=users.models.user_private_directory_path, verbose_name='Richiesta di tesseramento'),
        ),
    ]
