# Generated by Django 3.0.7 on 2020-06-16 16:33

from django.db import migrations
import private_storage.fields
import private_storage.storage.files
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200616_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='med_cert',
            field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=users.models.user_private_directory_path, verbose_name='Certificato medico'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='privacy',
            field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=users.models.user_private_directory_path, verbose_name='Privacy'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='attachment',
            field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=users.models.user_private_directory_path, verbose_name='Allegato'),
        ),
    ]
