# Generated by Django 3.0.6 on 2020-06-12 20:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criterium', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceCache',
            fields=[
                ('race', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='criterium.Race')),
                ('cache', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
