# Generated by Django 3.0.2 on 2020-02-01 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criterium', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='athlete',
            options={'verbose_name': 'Atleta', 'verbose_name_plural': 'Atleti/e'},
        ),
    ]
