# Generated by Django 3.0.6 on 2020-06-12 20:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criterium', '0002_racecache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racecache',
            name='cache',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
