# Generated by Django 3.0.6 on 2020-06-15 18:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criterium', '0003_auto_20200612_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='cache',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
