# Generated by Django 3.0.6 on 2020-06-15 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criterium', '0004_race_cache'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='cache',
        ),
    ]
