# Generated by Django 3.0.5 on 2020-04-22 21:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('streamblocks', '0003_auto_20200329_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventUpgrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Il titolo dell'aggiornamento", max_length=50, verbose_name='Titolo')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
                ('body', models.TextField(help_text='Accetta tag HTML.', verbose_name='Aggiornamento')),
            ],
            options={
                'verbose_name': 'Aggiornamento',
                'verbose_name_plural': 'Aggiornamenti',
            },
        ),
    ]
