# Generated by Django 3.0.2 on 2020-03-06 18:23

from django.db import migrations
import streamfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pagine', '0013_event_upgrade_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='carousel',
            field=streamfield.fields.StreamField(blank=True, default='[]', null=True, verbose_name='Galleria'),
        ),
    ]
