# Generated by Django 3.0.2 on 2020-03-06 22:30

from django.db import migrations
import streamfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pagine', '0014_event_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='carousel',
            field=streamfield.fields.StreamField(blank=True, default='[]', help_text='Una sola galleria, per favore, larghezza minima immagini 2048px', null=True, verbose_name='Galleria'),
        ),
        migrations.AlterField(
            model_name='event',
            name='carousel',
            field=streamfield.fields.StreamField(blank=True, default='[]', help_text='Una sola galleria, per favore, larghezza minima immagini 2048px', null=True, verbose_name='Galleria'),
        ),
    ]
