# Generated by Django 3.0.5 on 2020-04-22 21:52

from django.db import migrations, models
import django.db.models.deletion
import streamfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cronache', '0001_initial'),
        ('users', '0012_auto_20200422_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Il nome della società', max_length=50, verbose_name='Nome')),
                ('denomination', models.CharField(choices=[('ASD', 'Associazione Sportiva Dilettantistica'), ('SSD', 'Società Sportiva Dilettantistica')], max_length=4, verbose_name='Denominazione')),
                ('coni', models.CharField(blank=True, max_length=10, null=True, verbose_name='Registro CONI')),
                ('fidal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Affiliazione FIDAL')),
                ('fiscal_code', models.CharField(blank=True, max_length=11, null=True, verbose_name='Codice Fiscale')),
                ('iban', models.CharField(blank=True, max_length=27, null=True, verbose_name='Codice IBAN')),
                ('executive', models.ManyToManyField(related_name='society_executive', to='users.Profile', verbose_name='Dirigenti')),
                ('location', models.ForeignKey(help_text='Inserisce indirizzo e contatti', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cronache.Location', verbose_name='Sede')),
                ('president', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='society_president', to='users.Profile', verbose_name='Presidente')),
                ('trainers', models.ManyToManyField(related_name='society_trainers', to='users.Profile', verbose_name='Istruttori')),
            ],
            options={
                'verbose_name': 'Dati societari',
                'verbose_name_plural': 'Dati societari',
            },
        ),
        migrations.CreateModel(
            name='Convention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Il nome della convenzione', max_length=50, verbose_name='Nome')),
                ('slug', models.SlugField(editable=False, null=True, unique=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descrizione')),
                ('file_stream', streamfield.fields.StreamField(blank=True, default='[]', verbose_name='File')),
                ('location', models.ForeignKey(blank=True, help_text='Inserire indirizzo e contatti', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cronache.Location', verbose_name='Indirizzo')),
            ],
            options={
                'verbose_name': 'Convenzione',
                'verbose_name_plural': 'Convenzioni',
            },
        ),
    ]
