# Generated by Django 3.0.2 on 2020-02-06 23:01

from django.db import migrations
import streamfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('direzione', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutional',
            name='stream',
            field=streamfield.fields.StreamField(blank=True, default='[]', verbose_name='Blocchi'),
        ),
    ]
