# Generated by Django 3.0.2 on 2020-02-06 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direzione', '0002_institutional_stream'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paragraph',
        ),
    ]
