# Generated by Django 3.0.2 on 2020-02-07 15:38

from django.db import migrations
import streamfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('direzione', '0003_delete_paragraph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutional',
            name='stream',
            field=streamfield.fields.StreamField(blank=True, default='[]', verbose_name='Testo'),
        ),
    ]
