# Generated by Django 3.0.2 on 2020-02-07 18:31

from django.db import migrations
import streamfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('direzione', '0004_auto_20200207_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='convention',
            name='file_stream',
            field=streamfield.fields.StreamField(blank=True, default='[]', verbose_name='File'),
        ),
    ]
