# Generated by Django 3.0.2 on 2020-02-07 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direzione', '0005_convention_file_stream'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConventionUpload',
        ),
    ]
