# Generated by Django 3.0.2 on 2020-02-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direzione', '0006_delete_conventionupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutional',
            name='type',
            field=models.CharField(choices=[('1-IS', 'Iscrizioni'), ('2-ST', 'Storia'), ('3-PR', 'Privacy'), ('4-IN', 'Istruzioni')], max_length=4, null=True, verbose_name='Tipo'),
        ),
    ]
